### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by muhammad-7-10** [SiamSami/Avro-installer-for-Deepin#1]
Hello. I'm using Deepin 20.6. Untill this step (git clone git://github.com/sarim/ibus-avro.git), everything works fine. But this doesn't work.Please fix it. I have no internet issue.
![Screenshot_select-area_20230725095929](https://github.com/SiamSami/Avro-installer-for-Deepin/assets/140474747/d6e2e3ae-4992-4f8c-afb8-78e8ada57535)

**Comment by SiamSami** [comment]
Hello. Sorry for the extremely late reply. I was really busy last year and couldn't visit github at all and so was unable to see your issue. Again I apologize for replying this late.

The latest version of deepin doesn't support ibus-m17n which is required for avro to work. In other words, avro can't work on deepin anymore.

Thankfully, however, there is an alternative called Openbangla which works using fcitx5. You can take a look at this [guide](https://github.com/SiamSami/openbangla-deepin) for installing and setting up openbangla on deepin.
